# Generated by Django 4.2.14 on 2024-07-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasapp', '0002_alter_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hire',
            old_name='doctor_id',
            new_name='tech_id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
